version: 2
jobs:
  build:
    docker:
      - image: tardyp/sw_linux_build
    steps:
      - checkout
      - run:
          name: submodule
          command: git submodule update --init
      - run:
          name: build
          command: make all
      - store_artifacts:
          path: dist.tgz